#!/bin/bash
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
clear
echo "========================================"
echo ""
echo "        OpenSVH Project Rev.1           "
echo ""
echo "========================================"
echo ""

if [ -e "/var/log/auth.log" ]; then
    LOG="/var/log/auth.log";
fi
if [ -e "/var/log/secure" ]; then
    LOG="/var/log/secure";
fi

data=( `ps aux | grep -i dropbear | awk '{print $2}'`);
echo "====== Dropbear User Authenticated ======";
echo "ID  |  Username  |  IP Address";
echo "-------------------------------------";
cat $LOG | grep -i dropbear | grep -i "Password auth succeeded" > /tmp/login-db.txt;
for PID in "${data[@]}"
do
    cat /tmp/login-db.txt | grep "dropbear\[$PID\]" > /tmp/login-db-pid.txt;
    NUM=`cat /tmp/login-db-pid.txt | wc -l`;
    USER=`cat /tmp/login-db-pid.txt | awk '{print $10}'`;
    IP=`cat /tmp/login-db-pid.txt | awk '{print $12}'`;
    if [ $NUM -eq 1 ]; then
        echo "$PID - $USER - $IP";
    fi
done
echo "========================================"
echo ""
echo "====== OpenSSH User Authenticated ======";
echo "ID  |  Username  |  IP Address";
echo "-------------------------------------";
cat $LOG | grep -i sshd | grep -i "Accepted password for" > /tmp/login-db.txt
data=( `ps aux | grep "\[priv\]" | sort -k 72 | awk '{print $2}'`);

for PID in "${data[@]}"
do
    cat /tmp/login-db.txt | grep "sshd\[$PID\]" > /tmp/login-db-pid.txt;
    NUM=`cat /tmp/login-db-pid.txt | wc -l`;
    USER=`cat /tmp/login-db-pid.txt | awk '{print $9}'`;
    IP=`cat /tmp/login-db-pid.txt | awk '{print $11}'`;
    if [ $NUM -eq 1 ]; then
        echo "$PID - $USER - $IP";
    fi
done
echo "========================================"
echo ""
echo "====== Trojan User Authenticated ======";
trojanData=( `cat /var/log/trojan.log | grep -w 'authenticated as' | awk '{print $7}' | sort | uniq`);
for akun in "${trojanData[@]}"
do
trojanData2=( `lsof -n | grep -i ESTABLISHED | grep trojan | awk '{print $9}' | cut -d':' -f2 | grep -w 445 | cut -d- -f2 | grep -v '>127.0.0.1' | sort | uniq | cut -d'>' -f2`);
echo -n > /tmp/iptrojan.txt
for ip in "${trojanData2[@]}"
do
jum=$(cat /var/log/trojan.log | grep -w $akun | awk '{print $4}' | cut -d: -f1 | grep -w $ip | sort | uniq)
if [[ -z "$jum" ]]; then
echo > /dev/null
else
echo "$jum" > /tmp/iptrojan.txt
fi
done
jum2=$(cat /tmp/iptrojan.txt | nl)
echo "user : $akun";
echo "$jum2";
echo "========================================"
done
