#!/bin/bash
clear
uuid=$(cat /etc/trojan/uuid.txt)
IP=$(wget -qO- icanhazip.com);
domain=$OPENSVH_DOMAIN

if [[ "$IP" = "" ]]; then
    domain=$(cat /opt/opensvh.domain)
else
    domain=$IP
fi

if [[ "$domain" = "" ]]; then
    domain=$IP
else
    domain=$domain
fi

until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${user_EXISTS} == '0' ]]; do
    read -rp "Remarks: " -e user
    user_EXISTS=$(grep -w $user /etc/trojan/akun.conf | wc -l)

    if [[ ${user_EXISTS} == '1' ]]; then
        echo ""
        echo "A client with the specified name was already created, please choose another name."
        exit 1
    fi
done
read -p "Expired (days): " masaaktif
sed -i '/"'"$uuid"'"$/a\,"'"$user"'"' /etc/trojan/config.json
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
echo -e "### $user $exp" >> /etc/trojan/akun.conf
systemctl restart trojan
trojanlink="trojan://${user}@$domain:8880"
clear
echo -e ""
echo -e "=========================================="
echo -e ""
echo -e "          OpenSVH Project Rev.1           "
echo -e ""
echo -e "=========================================="
echo -e "Remarks        : ${user}"
echo -e "IP             : $IP"
echo -e "Host           : $OPENSVH_DOMAIN"
echo -e "Port           : 8880"
echo -e "Key            : ${user}"
echo -e "link           : ${trojanlink}"
echo -e "=========================================="
echo -e "Expired On     : $exp"
