#!/bin/bash
clear
trojanData=( `cat /etc/trojan/config.json | grep '^###' | cut -d ' ' -f 2`);
now=`date +"%Y-%m-%d"`
for user in "${trojanData[@]}"
do
    exp=$(grep -w "^### $user" "/etc/trojan/config.json" | cut -d ' ' -f 3)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(( (d1 - d2) / 86400 ))
    if [[ "$exp2" = "0" ]]; then
        sed -i "/^### $user $exp/,/^},{/d" /etc/trojan/config.json
    fi
done
systemctl restart trojan