#!/bin/sh
#
wget https://github.com/andikamc/badvpn-udpgw/archive/refs/tags/1.999.128.zip && unzip 1.999.128.zip
mv badvpn-udpgw-1.999.128/badvpn-udpgw /usr/bin/badvpn-udpgw
rm -rf badvpn-udpgw-1.999.128
chmod +x /usr/bin/badvpn-udpgw